import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/layout/Layout'
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedTeaxt from '@/components/animatedtext/AnimatedTeaxt'
import Link from 'next/link'
import Hireme from '@/components/Hireme/Hireme'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import Transition from '@/components/Transition'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head >

<Transition/>
      <main className={"flex  items-center text-dark w-full min-h-screen"}>

        <Layout className={"pt-0 md:!pt-16 sm:!pt-8"}>
          <div className="flex items-center justify-between w-full lg:flex-col-reverse ">
            <div className='w-1/2 md:w-full '>
              <Image src={profilePic} className='w-full h-auto md:inline-block md:w-full  md:mt-[15vh]   '
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                priority
              />
            </div>
            <div className='w-1/2 lg:w-full  flex flex-col items-center self-center'>
              <AnimatedTeaxt text={"Turning Vision Into Reality With Code And Design."} className='!text-6xl text-left lg:!text-center sm:!text-4xl sm:!text-center' />
              <p className='my-4 text-base font-medium lg:mt-[4vh] lg:text'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.

              </p>
              <div className='flex items-center self-start mt-2 lg:self-center lg:mt-[6vh]'>
                <Link href="/Aman deep sharma(1).pdf" target='_blank' className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg font-semibold text-lg hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark'>RESUME</Link>
                <Link href="mailto:amandeepsharma8944@gmail.com" className='ml-4 text-lg font-medium capitalize text-dark underline'>CONTACT </Link>
              </div>
            </div>
            <div  className='absolute right-8 bottom-8 inline-block w-24 lg:hidden'>      <Image src={lightBulb}  className='w-full h-auto'/> </div>
          </div>
        </Layout>

        <Hireme />
       
        <div>
        </div>

      </main>
    </>
  )
}
